[package]
name = "stringbuf"
version = "0.2.0"
authors = ["Joey Ezechiëls <joey.ezechiels@gmail.com>"]
license = "MIT"
description = "An efficient and easy-to-use library to append strings."
repository = "https://github.com/jjpe/stringbuf"

[dependencies]
